### ISSUE TITLE
error post running the scripts 

### ISSUE THREAD

**Issue by denver2020** [mhogeveen/er-quest-tracker#62]
hi,

after running the scripts and opening up http://localhost:3000, i get below error. am i doing something wrong? thanks 

![image](https://github.com/mhogeveen/er-quest-tracker/assets/45709415/a8d81824-a0d4-49f1-b78c-e7405365159d)

**Comment by mhogeveen** [comment]
Hi @denver2020,

The error is a message placed by me to warn users that the project is not complete and they can lose progress if they use it before it's fully done. You aren't doing anything wrong on your end.

Let me know if that clears thing up :)
